### ISSUE TITLE
[bug] `Show compressed size` does not affect module sizes

### ISSUE THREAD

**Issue by gabrielcsapo** [statoscope/statoscope#140] opened 2021-11-08 23:54 UTC
**Describe the bug**

When using `Show compressed size` it does not alter the module sizes which causes confusion when trying to find what is contributing to the uncompressed size.

<img width="1267" alt="Screen Shot 2021-11-08 at 3 50 56 PM" src="https://user-images.githubusercontent.com/1854811/140836412-a0b592d8-773c-47b9-8c7b-a5b2922c8f75.png">

**To Reproduce**
1. Go to 'the index of a report'
2. Click on 'hamburger menu'
<img width="303" alt="Screen Shot 2021-11-08 at 3 51 50 PM" src="https://user-images.githubusercontent.com/1854811/140836494-494b6f46-917f-480f-ae5c-d410d88ee159.png">
3. expand the main entry point Scroll to the modules section
4. Adding up all the modules does not equal the uncompressed size.

**Expected behavior**
Module sizes should be uncompressed

**Versions**:
 - Browser (for browser-bug): 
 - Webpack: "^5.58.2",
 - Statoscope: "^5.18.0"

**Comment by smelukov** [comment] 2021-11-09 05:52
> When using Show compressed size it does not alter the module sizes

I've checked that size of modules changes correctly depending on `Show compressed size` checkbox. Can't reproduce your bug (

> Adding up all the modules does not equal the uncompressed size.

The total size of a bundle is the total size of all its assets, not modules.

**Comment by gabrielcsapo** [comment] 2021-11-09 16:42
Ahh okay, that makes sense.

I guess my confusion is trying to figure out what asset is causing it to balloon to 17mb. When I try to expand assets I get the same file over and over again.

![Screen Shot 2021-11-09 at 8 41 07 AM](https://user-images.githubusercontent.com/1854811/140966631-40f6d4e3-1d22-403b-aed8-2c49db355d63.png)

**Comment by smelukov** [comment] 2021-11-09 18:18
You can click on main chunk to see module map. It will help you to figure out why your bundle so huge

**Comment by smelukov** [comment] 2021-11-17 18:03
@gabrielcsapo can we close the issue? )

**Comment by gabrielcsapo** [comment] 2021-11-17 18:23
Closing! Thanks @smelukov

**Closed** 2021-11-17 18:23 UTC
Labels: bug, need investigate
